### ISSUE TITLE
Led strip RBG (not RGB)

### ISSUE THREAD

**Issue by PanBlaza** [jnimmo/hass-dmx#65]
Firstly thanks a lot Jnimmo for a great app:)
Unfortunately, I have a little problem with it. I have dmx led strip which type is RBG (not RGB as you require) and when I want to choose some colour, it is never the one I needed

**Comment by Breina** [comment]
@PanBlaza I've implemented this feature [over at my fork](https://github.com/Breina/ha-artnet-led) using an extra `channel_setup`  configuration parameter.

**Comment by PanBlaza** [comment]
Still I don't know hot to:P
Could you help me with that: this is my file im very basic in programming :P

platform: dmx
    host: 192.168.0.150
    port: 6454
    universe: 0
    default_type: rgb
    default_level: 0
    devices:
      - channel: 1
        name: PIXEL1
      - channel: 4
        name: PIXEL2
      - channel: 7
        name: PIXEL3
      - channel: 10
        name: PIXEL4
      - channel: 13
        name: PIXEL5
      - channel: 16
        name: PIXEL6
      - channel: 19
        name: PIXEL7
           .
           .
           .
     - channel: 454
        name: PIXEL152
      - channel: 457
      
  - platform: group
    name: SOFA LEDY
    entities:
         - light.PIXEL108
         - light.PIXEL109
           .
           .
           .
         - light.PIXEL146
         - light.PIXEL147

**Comment by Breina** [comment]
First you will need to uninstall jnimmo's plugin and install mine to have this feature.

Your setup will look something like this:

```
light:
- platform: artnet_led
  host: 192.168.0.150
  port: 6454
  max_fps: 25
  refresh_every: 0
  universes:
    0:
      devices:
        - channel: 1
          name: PIXEL1
          type: rgb
          channel_size: 16bit
          output_correction: quadratic
          channel_setup: rbg
        - channel: 4
          name: PIXEL2
          type: rgb
          channel_size: 16bit
          output_correction: quadratic
          channel_setup: rbg
          ...
          ```
